# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d97479eb2827f5af7d510c763c2800fba75d68d7bbd95e513399e28830c17f1fd95f615ca9d729bc9eb2324d6f572c55ce1db907dac2e68c9d3e4d187b5bdf5

test:
  secret_key_base: 73d0f44810fe3b6f81350779c3529aff086e854bba169c479e801b454a84e19a80efd9e0d780042c303b73c21708bfafcd8342a9fd88f00616852f3aaaf4f236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
